// Import the JSX and style modules to be used for the page.
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

// Create the function for the post page template. Load in the postData
// object from the page props.
export default function Post({ postData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next.js Profile Page | {postData.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {postData.name}
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            {postData.content}
          </div>
        </div>
      </main>
    </div>
  );
}

// Provide a list of possible paths for the route.
export async function getStaticPaths() {
  // Fetch posts from the API.
  const res = await fetch('http://localhost:3000/api/posts')
  const postsData = await res.json()

  // Generate an array of paths. Each object follows a specific format:
  //   { params: [routeId]: [possibleValue] }
  const paths = postsData.map((postData) => {
    return {
      params: {
        postSlug: postData.slug
      }
    }
  });

  // Return the array of paths; fallback=false has the app 404 for any paths
  // not in this list.
  return {
    paths,
    fallback: false
  }
}

// Load page propeties as part of server-side pre-rendering.
export async function getStaticProps({ params }) {
  // Fetch the page data from the API.
  const res = await fetch('http://localhost:3000/api/posts/' + params.postSlug);
  const postData = await res.json();

  // Return the fetched data in the props object.
  return {
    props: {
      postData
    }
  };
}
